version: '3'
services:
  voting-app:
    image: voting-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
        - REDIS=redis
        - REDIS_PWD=redispassword
    depends_on:
      - redis
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:80|| exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
  redis:
    image: redis
    command: redis-server --requirepass redispassword