name: CI Pipeline

on:
  workflow_dispatch: # Manually trigger workflow
#  push:
#    branches:
#      - main

jobs:
  lint_code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Lint Python code
        run: |
          pip install flake8
          flake8 .

  security_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Bandit
        run: pip install bandit

      - name: Run security scan
        run: bandit -r .

  build_packer:
    runs-on: ubuntu-latest

    needs: [lint_code, security_scan]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Packer
        run: |
          wget https://releases.hashicorp.com/packer/1.7.6/packer_1.7.6_linux_amd64.zip
          unzip packer_1.7.6_linux_amd64.zip
          sudo mv packer /usr/local/bin/

      - name: Build Packer
        run: packer build your_packer_template.json

  docker_push:
    runs-on: ubuntu-latest

    needs: build_packer

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t your_docker_image_name .
          docker push your_docker_image_name

  semantic_release:
    runs-on: ubuntu-latest

    needs: docker_push

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install Semantic Release
        run: npm install -g semantic-release

      - name: Run Semantic Release
        run: semantic-release

